### ISSUE TITLE
Use releases to provide reproducibility information

### ISSUE THREAD

**Issue by wdconinc** [eic/estarlight#8]
eSTARlight does not currently have any releases. This means that we currently cannot specify that a particular HepMC3 input file for full productions was generated with e.g. v1.2.3 of eSTARlight, and we are likely to get information that is simply "we used the main branch", "we used the main branch on August 13, 2022", or (at best) "we used commit 9f9e239 without local changes". While the latter is specific it does not make any time ordering manifest in the way that a version number does. In order to include eSTARlight in software environments provided to the EIC community, I'd like to suggest a version numbering scheme. [Semantic versioning](https://semver.org) would be a common approach for a version number scheme.

**Comment by zsweger** [comment]
Hi Wouter, I want to address this and start using semantic versioning. Do I just include version information in the README.md and a new VERSION file? Do you recommend starting the versioning from the current release at Version 1.0.0?

**Comment by wdconinc** [comment]
To be honest, I'd stay away from any version info inside the files of the repository (needs to get updated and invariably gets out of date) and just create a release using GitHub's functionality. That creates a branch but also conveniently adds a change log to the release notes.

**Comment by wdconinc** [comment]
Starting from 1.0.0 is perfectly fine (unless there's a version you've used extensively that would merit that version). But again, I wouldn't overthink this too much.

**Comment by zsweger** [comment]
I believe I've added releases. Wouter, could you review this to make sure it's what we need. 
So from now on, is it standard practice to tag the code with a major+minor+patch version number for each and every push to the main branch?

**Comment by wdconinc** [comment]
Looks good :-) I'd just change the release name at https://github.com/eic/estarlight/releases from "Beginning of Releases" to "v1.0.0: " followed by some spiffy release name or a very brief summary. This is what shows up on the right side bar of https://github.com/eic/estarlight.

No need to release on every push. Just whenever you feel like it or features deserve it. Some projects release on a time-based cycle, so you can set a reminder for every quarter or so and release depending on whether there were major, minor, or patch changes. Bugfixes can be released more frequently in between.

Only new releases may make it into downstream distributions, such as eic-shell. I'd simply suggest that for major simulation productions you ensure that there is a clean release people are using.

**Comment by zsweger** [comment]
Thank you for the info! I've updated the release name so I'll close this issue. Let me know if anything else is suggested to keep up with EIC standard practice.
